const $=id=>document.getElementById(id);
let state={dep:null,dst:null,pos:null,aircraft:null,lastQuote:null};
function findAirport(code){return window.AIRPORTS.find(a=>a.code===code)}
function setDefaults(){state.dep=findAirport('YPJT');state.dst=findAirport('YCAI');state.pos=findAirport('YPJT');state.aircraft=window.AIRCRAFT.find(a=>a.id==='C90');$('departureSearch').value='Jandakot';$('destinationSearch').value='Callion';$('positionSearch').value='Jandakot';updateBadges();renderAircraft();refresh();renderRecent();}
function searchAirports(q){q=(q||'').toLowerCase().trim(); if(!q) return window.AIRPORTS.slice(0,8); return window.AIRPORTS.filter(a=>(a.code+' '+a.name+' '+a.type+' '+(a.fuel||'')).toLowerCase().includes(q)).slice(0,10)}
function bindSearch(inputId,resultId,onPick){const input=$(inputId),box=$(resultId); input.addEventListener('input',()=>{const list=searchAirports(input.value); box.innerHTML=list.map(a=>`<div class="result-item" data-code="${a.code}"><strong>${a.name} (${a.code})</strong><span>${a.type} · ${a.fuel||'Fuel check required'}</span></div>`).join(''); box.classList.add('show');}); box.addEventListener('click',e=>{const item=e.target.closest('.result-item'); if(!item) return; const ap=findAirport(item.dataset.code); onPick(ap); input.value=ap.name; box.classList.remove('show'); updateBadges(); refresh();}); input.addEventListener('focus',()=>input.dispatchEvent(new Event('input'))); document.addEventListener('click',e=>{if(!input.contains(e.target)&&!box.contains(e.target)) box.classList.remove('show')});}
function updateBadges(){$('depBadge').textContent=`${state.dep.name} (${state.dep.code})`;$('dstBadge').textContent=`${state.dst.name} (${state.dst.code})`}
function renderAircraft(){const rec=recommendAircraft({dep:state.dep,dst:state.dst,pax:Number($('pax').value||1),returnFlight:$('returnFlight').checked});$('recommendedText').textContent=`Recommended: ${rec.name}`; $('aircraftCards').innerHTML=window.AIRCRAFT.map(a=>{const q=calcQuote({dep:state.dep,dst:state.dst,pos:state.pos,aircraft:a,pax:Number($('pax').value||1),returnFlight:$('returnFlight').checked,flatLanding:$('flatLanding').value,paxLanding:$('paxLanding').value,waitingFee:$('waitingFee').value,margin:$('margin').value}); return `<button type="button" class="aircraft-card ${a.id===state.aircraft.id?'selected':''} ${a.id===rec.id?'recommended':''}" data-id="${a.id}"><strong>${a.name}</strong><span>${a.pax} pax · ${a.speed} kt · ${money(a.rate)}/hr<br>Est. ${money(q.total)} · ${timeFmt(q.hours)}</span></button>`}).join('');}
function inputs(){return {dep:state.dep,dst:state.dst,pos:state.pos,aircraft:state.aircraft,pax:Number($('pax').value||1),returnFlight:$('returnFlight').checked,flatLanding:Number($('flatLanding').value||0),paxLanding:Number($('paxLanding').value||0),waitingFee:Number($('waitingFee').value||0),margin:Number($('margin').value||0)}}
function refresh(){renderAircraft(); const q=calcQuote(inputs()); drawMap(state.dep,state.dst,state.pos,state.aircraft,q);}
function calculate(){const q=calcQuote(inputs());state.lastQuote=q;const d=new Date();$('quoteRef').textContent=quoteRef();$('quoteDate').textContent=d.toLocaleDateString('en-AU',{day:'2-digit',month:'short',year:'numeric'});$('quoteRoute').textContent=`${state.dep.code} ${$('returnFlight').checked?'↔':'→'} ${state.dst.code}`;$('quoteTotal').textContent=money(q.total);$('qAircraft').textContent=state.aircraft.name;$('qPax').textContent=$('pax').value;$('qDistance').textContent=`${Math.round(q.totalNm)} nm`;$('qTime').textContent=timeFmt(q.hours);$('breakdown').innerHTML=`<div class="brow"><span>Charter flying</span><strong>${money(q.charter)}</strong></div><div class="brow"><span>Landing fees (${q.landings} landing${q.landings===1?'':'s'})</span><strong>${money(q.landingCost)}</strong></div><div class="brow"><span>Waiting / overnight</span><strong>${money(Number($('waitingFee').value||0))}</strong></div><div class="brow"><span>Subtotal</span><strong>${money(q.subtotal)}</strong></div><div class="brow"><span>Margin</span><strong>${money(q.marginAmt)}</strong></div><div class="brow"><span>GST</span><strong>${money(q.gst)}</strong></div><div class="brow total"><span>Total inc. GST</span><strong>${money(q.total)}</strong></div>`;$('resultPanel').classList.remove('hidden');saveRecent(q);renderRecent();setEmailLink(q);setTimeout(()=>$('resultPanel').scrollIntoView({behavior:'smooth',block:'start'}),80)}
function setEmailLink(q){const body=`Legendaire Charter Pro quote%0D%0A%0D%0ARoute: ${state.dep.name} (${state.dep.code}) ${$('returnFlight').checked?'return to/from':'to'} ${state.dst.name} (${state.dst.code})%0D%0AAircraft: ${state.aircraft.name}%0D%0APassengers: ${$('pax').value}%0D%0ADistance: ${Math.round(q.totalNm)} nm%0D%0AFlight time: ${timeFmt(q.hours)}%0D%0ATotal inc GST: ${money(q.total)}%0D%0A%0D%0AIndicative only, subject to operator confirmation.`;$('emailBtn').href=`mailto:?subject=Charter quote ${state.dep.code}-${state.dst.code}&body=${body}`}
function saveRecent(q){const item={t:Date.now(),route:`${state.dep.code}-${state.dst.code}`,aircraft:state.aircraft.name,total:money(q.total)};const list=JSON.parse(localStorage.getItem('lcp_recent')||'[]');list.unshift(item);localStorage.setItem('lcp_recent',JSON.stringify(list.slice(0,6)))}
function renderRecent(){const list=JSON.parse(localStorage.getItem('lcp_recent')||'[]');$('recentQuotes').innerHTML=list.length?list.map(i=>`<div class="recent-item"><div><strong>${i.route}</strong><br><span>${i.aircraft}</span></div><strong>${i.total}</strong></div>`).join(''):'<span style="color:var(--muted);font-size:.86rem">No recent quotes yet.</span>'}
function applyPreset(p){if(p==='fifo'){ $('margin').value=15;$('flatLanding').value=200;$('paxLanding').value=0;} if(p==='freight'){ $('margin').value=20;$('pax').value=1;$('flatLanding').value=200;} if(p==='corporate'){ $('margin').value=18;$('flatLanding').value=250;} if(p==='aog'){ $('margin').value=25;$('flatLanding').value=200;} refresh();}
function init(){bindSearch('departureSearch','departureResults',ap=>state.dep=ap);bindSearch('destinationSearch','destinationResults',ap=>state.dst=ap);bindSearch('positionSearch','positionResults',ap=>state.pos=ap);$('aircraftCards').addEventListener('click',e=>{const b=e.target.closest('.aircraft-card'); if(!b) return; state.aircraft=window.AIRCRAFT.find(a=>a.id===b.dataset.id); refresh();});['pax','returnFlight','flatLanding','paxLanding','waitingFee','margin'].forEach(id=>$(id).addEventListener('input',refresh));$('swapRoute').addEventListener('click',()=>{[state.dep,state.dst]=[state.dst,state.dep];$('departureSearch').value=state.dep.name;$('destinationSearch').value=state.dst.name;updateBadges();refresh();});document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));$('calculateBtn').addEventListener('click',calculate);$('printBtn').addEventListener('click',()=>window.print());$('copyBtn').addEventListener('click',async()=>{if(!state.lastQuote)calculate();const q=state.lastQuote;const txt=`${state.dep.code} ${$('returnFlight').checked?'return':'to'} ${state.dst.code} · ${state.aircraft.name} · ${$('pax').value} pax · ${timeFmt(q.hours)} · ${money(q.total)} inc GST`;try{await navigator.clipboard.writeText(txt);$('copyBtn').textContent='Copied';setTimeout(()=>$('copyBtn').textContent='Copy Summary',1400)}catch(e){alert(txt)}});$('clearRecent').addEventListener('click',()=>{localStorage.removeItem('lcp_recent');renderRecent()}); if('serviceWorker' in navigator) navigator.serviceWorker.register('./service-worker.js').catch(()=>{});setDefaults();}
init();
